### ISSUE TITLE
Too much data for declared Content-Length error in DELETE post (Chapter 3)

### ISSUE THREAD

**Issue by particle1331** [PacktPublishing/Building-Data-Science-Applications-with-FastAPI#4]
I'm getting the following error message when testing out [chapter3_response_path_parameters_02.py](https://github.com/PacktPublishing/Building-Data-Science-Applications-with-FastAPI/blob/main/chapter3/chapter3_response_path_parameters_02.py). 
```
h11._util.LocalProtocolError: Too much data for declared Content-Length
``` 
This looks like a [known issue](https://github.com/tiangolo/fastapi/issues/2253). I'm guessing its because `content-length: 4` in the response when returning `None`. Returning `Response(status_code=status.HTTP_204_NO_CONTENT)` seems to fix the issue (content-length zero in this case).

<img width="571" alt="Screen Shot 2021-12-25 at 5 02 48 AM" src="https://user-images.githubusercontent.com/54845098/147372248-946c17a1-d39c-4bee-9a41-65d73b8e0ff1.png">

**Comment by frankie567** [comment]
Hi @particle1331!

Yes, it's a (yet) unresolved issue in FastAPI. Here is the main issue tracking this: https://github.com/tiangolo/fastapi/issues/2832

The shortest solution is the following:

```py
@app.delete("/posts/{id}", status_code=status.HTTP_204_NO_CONTENT, response_class=Response)
async def delete_post(id: int):
    posts.pop(id, None)
    return None
```

I made the choice to not mention it in the book because it'll (hopefully) be fixed at some point.

Note also that it happens when Uvicorn run the `h11` HTTP implementation is used. When using the `httptools` implementation, the error is ignored. If you installed Uvicorn with `uvicorn[standard]`, `httptools` should be used by default. You can try to force the implementation using the `--http` flag:

```
uvicorn --http httptools  chapter3_response_path_parameters_02:app
```
